In [2]:
#conditional

In [8]:
name=input("Enter Name: ")
if name=="durga":
    print("Hello durga Good Morning.")
else:
    print("Hello Guest Good Morning.")
print("How Are You!!!")

Enter Name:  sagar


Hello Guest Good Morning.
How are you!!!


In [24]:
brand=input("Enter Your Favourite Brand: ")
if brand=="RC":
    print("It is Children Brand")
elif brand=="KF":
    print("It is not that much kick")
elif brand=="FO":
    print("Buy One Get Free One")
else:
    print("Other Brands Are Not Recommended")

Enter Your Favourite Brand:  FO


Buy One Get Free One


In [2]:
#Assignment
#Q1) Write a program to find greatest num among 2 num.
#Q2) Write a program to find greatest among 3 num.
#Q3) 

In [4]:
#Q1
a=int(input("Enter a: "))
b=int(input("Enter b: "))
if a>b:
    print("a is greater than b.")
else:
    print("b is greater than a.")

Enter a:  5
Enter b:  6


b is greater than a.


In [10]:
#Q2
a=int(input("Enter a: "))
b=int(input("Enter b: "))
c=int(input("Enter c: "))
if a>b:
    if a>c:
        print("a is greatest.")
    else:
        print("c is greatest.")
elif b>c:
    print("b is greatest.")
else:
    print("c is greatest.")

Enter a:  7
Enter b:  6
Enter c:  5


a is greatest.


In [12]:
#Q3) smallest among 2 
a=int(input("Enter a: "))
b=int(input("Enter b: "))
if(a<b):
    print("a is smaller than b.")
else:
    print("b is smaller than a.")

Enter a:  5
Enter b:  6


a is smaller than b.


In [18]:
#Q4) smallest among 3
a=int(input("Enter a: "))
b=int(input("Enter b: "))
c=int(input("Enter c: "))
if(a<b and a<c):
    print("a is smallest.")
elif(b<a and b<c):
    print("b is smallest.")
else:
    print("c is smallest.")

Enter a:  6
Enter b:  5
Enter c:  4


c is smallest.


In [20]:
#Q5)even or odd
a=int(input("Enter a Number: "))
if(a%2==0):
    print("Input Number is even.")
else:
    print("Input Number is odd.")

Enter a Number:  6


Input Number is even.


In [24]:
#Q6)if number is between 1 to 100
a=int(input("Enter a Number: "))
if(a>=1 and a<=100):
    print("Number is between 1 to 100.")
else:
    print("Number is not between 1 to 100.")

Enter a Number:  101


Number is not between 1 to 100.


In [46]:
#Q7)single digit number input and print its value in english word
a=int(input("Enter a Number between 1 to 9: "))
if a==1:
    print("One.")
elif a==2:
    print("Two.")
elif a==3:
    print("Three.")
elif a==4:
    print("Four.")
elif a==5:
    print("Five.")
elif a==6:
    print("Six.")
elif a==7:
    print("Seven.")
elif a==8:
    print("Eight.")
elif a==9:
    print("Nine.")
else:
    print("Number is Invalid.")

Enter a Number between 1 to 9:  9


Nine.


In [51]:
for i in range(3):
    print(i)

0
1
2


In [53]:
bool("False")

True

In [55]:
bool()

False

In [57]:
bool(5)

True

In [59]:
list("123")

['1', '2', '3']

In [61]:
x=[1,2,3]
print(x is x[:])

False


In [67]:
a=10
b=50
print(a and b)

50


In [81]:
a=10
b=50
print(a or b)

10


In [89]:
for i in range(1,5,3):
    print(i,end=",")

1,4,

In [91]:
10//3

3

In [93]:
10/3

3.3333333333333335

In [95]:
x=None
if x:
    print("Yes")
else:
    print("No")

No


In [97]:
x=10
while x>5:
    x-=1
    if x==7:
        continue
    print(x)

9
8
6
5


In [99]:
a=["Learn","Quiz","Practice","Contribute"]
b=a
c=a[:]

b[0]="Code"
c[1]="Mcq"

count=0
for c in(a,b,c):
    if c[0]=="Code":
        count+=1
    if c[1]=="Mcq":
        count+=10
print(count)

12


In [2]:
#iteration

In [4]:
s="Hello world"
for x in s:
    print(x)

H
e
l
l
o
 
w
o
r
l
d


In [8]:
#Q1 Write a python program to find the sum of the first ten natural number using for loop
#Q2 WAP to print all even number between 1 to 20 using for loop
#Q3 WAP to calculate the factorial of a given number using for loop
#Q4 WAP to print the square of numbers from 21 to 30 using for loop 

In [16]:
#1 sum of first ten natural num
for x in range(1,11):
    print(x)


1
2
3
4
5
6
7
8
9
10


In [40]:
#2 even no btwn 1 to 20
for x in range(2,21):
    if(x%2==0):s
        print(x)

2
4
6
8
10
12
14
16
18
20


In [34]:
#3 factorial
a=int(input("Enter a number: "))
fact=1
for x in range (1,a+1):
    fact=fact*x
print(fact)

Enter a number:  5


120


In [36]:
#Q4 WAP to print the square of numbers from 21 to 30 using for loop 
for x in range (21,31):
    print(x*x)

441
484
529
576
625
676
729
784
841
900


In [42]:
s=input("Enter some string.")
i=0
for x in s:
    print("The character present at",i,"index is:",x)
    i=i+1

Enter some string. sagar


The character present at 0 index is: s
The character present at 1 index is: a
The character present at 2 index is: g
The character present at 3 index is: a
The character present at 4 index is: r


In [62]:
s=input("Enter some string.")
print(s[:5:2])

Enter some string. sagar


sgr


In [64]:
for x in range(10):
    print("sagar")

sagar
sagar
sagar
sagar
sagar
sagar
sagar
sagar
sagar
sagar


In [66]:
for x in range(101):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [78]:
import numpy as np
vector_row=np.array([1,2,3])
vector_col=np.array([[1],[2],[3]])
print(vector_row)
print(vector_col)

[1 2 3]
[[1]
 [2]
 [3]]


In [82]:
import numpy as np
x=np.array([[1,2],[1,2],[1,2]])
print(x)

[[1 2]
 [1 2]
 [1 2]]


In [106]:
import numpy as np
from scipy import sparse
#creating matrix
matrix = np.array([[0, 0],[0, 1],[3, 0]])
#create a compressed sparse row(csr) matrix
sparse_matrix = sparse.csr_matrix(matrix)
print(sparse_matrix)

  (1, 1)	1
  (2, 0)	3


In [118]:
import numpy as np
from scipy import sparse
vector=np.array([1,2,3,4,5,6])
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
vector[3]

4

In [120]:
matrix[1,2]

6